package lab3.ex1;
/*
 * This Java source file was generated by the Gradle 'init' task
 */
public class Book {
	private String chapters[];
	private static final int DEFAULT_CHAPTERS = 10;
	public Book () {
		chapters = new String[DEFAULT_CHAPTERS];
		for (int i = 0; i < chapters.length; i++)
			chapters[i] = "Chapter " + i;
	}
	public Book(String argument[]) {
		chapters = argument;		
	}
	public String getChapter(int i) {
		if (i < 0 || i >= chapters.length){
			return "Invalid chapter";
		}
		else {
			return chapters[i];
		}
		
	}
	public String[] getChapters() {
		return chapters;
	}
}

